In [1]:
import numpy as np
import itertools as it
import src.main as main

In [2]:
prod = list(it.product(range(2), repeat=4**2))
len(prod)


65536

In [3]:
a = np.asarray(prod[456])
a

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0])

In [4]:
np.matrix(a.reshape((4,4)))

matrix([[0, 0, 0, 0],
        [0, 0, 0, 1],
        [1, 1, 0, 0],
        [1, 0, 0, 0]])

In [5]:
m = np.matrix(a)

In [6]:
m = np.random.randint(2, size=(4,4))
m

array([[0, 0, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 1, 1],
       [0, 0, 0, 0]])

In [7]:
m[1, 0]

0

In [8]:
m == m[0,:]

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [9]:
tb = m == m[3,:]
tb

array([[ True,  True, False, False],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [ True,  True,  True,  True]])

In [10]:
tb = tb.all(1)
tb

array([False,  True, False,  True])

In [11]:
tb = np.delete(tb, 3)
tb

array([False,  True, False])

In [12]:
# np.all(tb, axis=1)

In [13]:
matrix = np.array(([1,1,0,1,0,0],[1,0,0,1,1,0],[0,1,1,0,1,1],[1,0,1,1,0,0],[0,1,0,1,0,1],[0,0,1,0,1,1]))

In [14]:
np.all(matrix == matrix[0,:], 1)

array([ True, False, False, False, False, False])

In [15]:
matrix = np.array(([5588, 1, 6312, 7711], [2986, 5669, 6793, 2317], [3479, 7200, 8358, 1], [7879, 4766, 2297, 5679]))
pos = row, column = 2, 2
value = 0

In [16]:
matrix[pos]

8358

## NaN matrix

In [17]:
a = np.empty((6,6))
a[:] = np.nan
a

array([[nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan]])

In [18]:
for i in range(1, len(a)-1):
        
    print(a[0][i-1: i+2])

[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]


In [19]:
a[0][1-1: 1+2]

array([nan, nan, nan])

In [20]:
np.any(a[0][1-1: 1+2])

True

In [21]:
np.isnan(np.nan)

True

In [22]:
np.nan == None

False

In [23]:
x = main.generate_matrix(8)
x[0]

array([[   1, 8606, 2484,    1, 3025, 4491, 1157, 7190],
       [   1, 5428, 2187, 6565,    0, 8763, 6070, 1757],
       [3820,    1,    0, 1788, 8901, 7037, 4748, 1807],
       [   0, 8756, 4319, 1764, 6267,    1, 5911,    0],
       [5159, 6302,    1, 1388, 2844, 9355, 7489, 9031],
       [8383, 9769, 7564, 3189, 4354, 2050, 7770,    0],
       [9864,    1, 2871,    1, 2142,    1,    0,    0],
       [8934,    0, 9943,    1, 9541, 2164,    1, 7051]])

In [24]:
z = main.Constraint_propagations(x)
z[0]

[[   1 8606 2484    1 3025 4491 1157 7190]
 [   1 5428 2187 6565    0 8763 6070 1757]
 [   0    1    0 1788 8901 7037 4748 1807]
 [   0 8756 4319 1764 6267    1 5911    0]
 [   1    0    1 1388 2844 9355 7489    1]
 [8383 9769 7564    0 4354 2050 7770    0]
 [   1    1    0    1    0    1    0    0]
 [8934    0 9943    1 9541 2164    1    1]]
[[   1 8606 2484    1 3025 4491 1157 7190]
 [   1 5428 2187 6565    0 8763 6070 1757]
 [   0    1    0 1788 8901 7037 4748 1807]
 [   0 8756 4319 1764 6267    1 5911    0]
 [   1    0    1 1388 2844 9355 7489    1]
 [   0 9769 7564    0 4354 2050 7770    0]
 [   1    1    0    1    0    1    0    0]
 [   0    0 9943    1 9541    0    1    1]]
[[   1 8606 2484    1 3025 4491 1157 7190]
 [   1 5428 2187 6565    0 8763 6070 1757]
 [   0    1    0 1788 8901 7037 4748 1807]
 [   0 8756 4319 1764 6267    1 5911    0]
 [   1    0    1 1388 2844 9355 7489    1]
 [   0 9769 7564    0 4354 2050 7770    0]
 [   1    1    0    1    0    1    0    0]
 [   0   

array([[   1, 8606, 2484,    1, 3025, 4491, 1157, 7190],
       [   1, 5428, 2187, 6565,    0, 8763, 6070, 1757],
       [   0,    1,    0, 1788, 8901, 7037, 4748, 1807],
       [   0, 8756, 4319, 1764, 6267,    1, 5911,    0],
       [   1,    0,    1, 1388, 2844, 9355, 7489,    1],
       [   0, 9769, 7564,    0,    1, 2050, 7770,    0],
       [   1,    1,    0,    1,    0,    1,    0,    0],
       [   0,    0,    1,    1,    0,    0,    1,    1]])

In [25]:
(z[0][0] == 0).sum()

0

In [26]:
(z[0][0] != 0) & (z[0][0] != 1)

array([False,  True,  True, False,  True,  True,  True,  True])

In [27]:
z[0][0][(z[0][0] != 0) & (z[0][0] != 1)] = 1

In [28]:
z[0]

array([[   1,    1,    1,    1,    1,    1,    1,    1],
       [   1, 5428, 2187, 6565,    0, 8763, 6070, 1757],
       [   0,    1,    0, 1788, 8901, 7037, 4748, 1807],
       [   0, 8756, 4319, 1764, 6267,    1, 5911,    0],
       [   1,    0,    1, 1388, 2844, 9355, 7489,    1],
       [   0, 9769, 7564,    0,    1, 2050, 7770,    0],
       [   1,    1,    0,    1,    0,    1,    0,    0],
       [   0,    0,    1,    1,    0,    0,    1,    1]])