In [1]:
import numpy as np
import itertools as it
import random
import main ,solver

In [2]:
prod = list(it.product(range(2), repeat=4**2))
len(prod)

65536

In [3]:
b = bin((2**(4**2))-16575).removeprefix("0b").zfill(4**2)
b = [char for char in b]
b

['1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1']

In [4]:
b = np.asarray(b).astype(int).reshape((4, 4))
b

array([[1, 0, 1, 1],
       [1, 1, 1, 1],
       [0, 1, 0, 0],
       [0, 0, 0, 1]])

In [5]:
sha = wi, hi =  4, 4
for i in range(2**(wi**2)):
    b = bin(i).removeprefix("0b").zfill(wi**2)
    b = [char for char in b]
    b = np.asarray(b).astype(int).reshape(sha)
    print()

In [6]:
a = np.asarray(prod[456])
a

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0])

In [7]:
np.matrix(a.reshape((4,4)))

matrix([[0, 0, 0, 0],
        [0, 0, 0, 1],
        [1, 1, 0, 0],
        [1, 0, 0, 0]])

In [8]:
m = np.matrix(a)

In [9]:
m = np.random.randint(2, size=(4,4))
m

array([[1, 0, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 0],
       [0, 0, 0, 1]])

In [10]:
m[1, 0]

0

In [11]:
m == m[0,:]

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [ True, False, False,  True],
       [False,  True,  True, False]])

In [12]:
tb = m == m[3,:]
tb

array([[False,  True,  True, False],
       [ True, False, False,  True],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [13]:
tb = tb.all(1)
tb

array([False, False, False,  True])

In [14]:
tb = np.delete(tb, 3)
tb

array([False, False, False])

In [15]:
# np.all(tb, axis=1)

In [16]:
matrix = np.array(([1,1,0,1,0,0],[1,0,0,1,1,0],[0,1,1,0,1,1],[1,0,1,1,0,0],[0,1,0,1,0,1],[0,0,1,0,1,1]))

In [17]:
np.all(matrix == matrix[0,:], 1)

array([ True, False, False, False, False, False])

In [18]:
matrix = np.array(([5588, 1, 6312, 7711], [2986, 5669, 6793, 2317], [3479, 7200, 8358, 1], [7879, 4766, 2297, 5679]))
pos = row, column = 2, 2
value = 0

In [19]:
matrix[pos]

8358

## NaN matrix

In [20]:
a = np.empty((6,6))
a[:] = np.nan
a

array([[nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan]])

In [21]:
for i in range(1, len(a)-1):
        
    print(a[0][i-1: i+2])

[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]


In [22]:
a[0][1-1: 1+2]

array([nan, nan, nan])

In [23]:
np.any(a[0][1-1: 1+2])

True

In [24]:
np.isnan(np.nan)

True

In [25]:
np.nan == None

False

In [31]:
xm = main.generate_matrix(6)
xm[0]

array([[3860, 9729, 9433, 1581, 1414, 3128],
       [6607, 8223, 7042, 1230, 3713, 4197],
       [8878, 7389, 3493, 7122, 1880, 8248],
       [3574, 8512, 3094, 4760, 5596, 3686],
       [4904, 3583, 9728, 9726, 8984, 9122],
       [5121, 5829, 8256, 5479, 3519, 3053]])

In [28]:
solver.Backtrack_Based_Search(xm[0])

[[3332 4788 8581 8186]
 [9976 7061 6764 1309]
 [8153 5066 9913 2516]
 [9250 8922 3240 4353]]

[[3332 4788 8581 8186]
 [9976 7061 6764 1309]
 [8153 5066 9913 2516]
 [9250 8922 3240 4353]]

[[3332 4788 8581 8186]
 [9976 7061 6764 1309]
 [8153 5066 9913 2516]
 [9250 8922 3240 4353]]

[[3332 4788 8581 8186]
 [9976 7061 6764 1309]
 [8153 5066 9913 2516]
 [9250 8922 3240 4353]]

[[3332 4788 8581 8186]
 [9976 7061 6764 1309]
 [8153 5066 9913 2516]
 [9250 8922 3240 4353]]

[[3332 4788 8581 8186]
 [9976 7061 6764 1309]
 [8153 5066 9913 2516]
 [9250 8922 3240 4353]]

[[3332 4788 8581 8186]
 [9976 7061 6764 1309]
 [8153 5066 9913 2516]
 [9250 8922 3240 4353]]

[[3332 4788 8581 8186]
 [9976 7061 6764 1309]
 [8153 5066 9913 2516]
 [9250 8922 3240 4353]]

[[3332 4788 8581 8186]
 [9976 7061 6764 1309]
 [8153 5066 9913 2516]
 [9250 8922 3240 4353]]

[[3332 4788 8581 8186]
 [9976 7061 6764 1309]
 [8153 5066 9913 2516]
 [9250 8922 3240 4353]]

[[3332 4788 8581 8186]
 [9976 7061 6764 1309]
 [8153 5066 99

In [ ]:
z = solver.Constraint_propagations(xm)
z[0]

array([[1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
(z[0][0] == 0).sum()

2

In [ ]:
(z[0][0] == 1)

array([ True,  True, False,  True,  True, False,  True,  True])

In [ ]:
(z[0][0] != 0) | (z[0][0] != 1)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
(z[0] != 0) & (z[0] != 1)

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [ ]:
((z[0][0] != 0) & (z[0][0] != 1)).sum()

0

In [ ]:
z[0][3][(z[0][3] != 0) & (z[0][3] != 1)] = 1

In [ ]:
z[0][(z[0] != 0) & (z[0] != 1)]

array([], dtype=int64)

In [ ]:
z[0].flatten()
x, y = np.where(z[0] == 2062)
ps = int(x), int(y)
print(ps)

TypeError: only size-1 arrays can be converted to Python scalars

In [ ]:
z[0] == 2062

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False]])

In [ ]:
n = np.array(([1 ,1, 1, 0, 0 ,0],
                [1 ,1, 1, 0, 0 ,0],
                [1 ,1, 1, 0, 0 ,0],
                [0 ,0, 0, 1, 1 ,1],
                [0 ,0, 0, 1, 1 ,1],
                [0 ,0, 0, 1, 1 ,1]))
n

array([[1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])

In [ ]:
h1 = np.array(([1, 1, 0, 1, 0, 1, 0, 1]))
h2 = np.array(([1, 1, 0, 1, 2343, 1, 0, 4543]))

In [ ]:
equal_mask = h1 == h2
equal_mask

array([ True,  True,  True,  True, False,  True,  True, False])

In [ ]:
filled_mask = ((h2 == 0) | (h2 == 1))
filled_mask

array([ True,  True,  True,  True, False,  True,  True, False])

In [ ]:
np.all(h1[filled_mask] == h2[filled_mask],)

True

In [ ]:
np.where(filled_mask == False)[0]

array([4, 5])

In [ ]:
h1[np.where(filled_mask == False)[0]]

array([0, 1])

In [ ]:
np.flip(h1[np.where(filled_mask == False)[0]])

array([1, 0])

In [ ]:
np.where(filled_mask == False)

(array([4, 7]),)

In [ ]:
[not elem for elem in filled_mask]

[False, False, False, False, True, True, False, False]

In [ ]:
h2[[not elem for elem in filled_mask]] = np.flip(h1[np.where(filled_mask == False)[0]])
h2

array([1, 1, 0, 1, 1, 0, 0, 1])